version: '3.4'

services:
  bugsfrontend:
    image: ${DOCKER_REGISTRY-}bugsfrontend
    build:
      context: .
      dockerfile: BugsFrontend/Dockerfile

  bugsapi:
    image: ${DOCKER_REGISTRY-}bugsapi
    build:
      context: .
      dockerfile: BugsApi/Dockerfile
    ports:
     - "8080:80" 
    depends_on:
     - database

  database:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    ports:
     - "1433:1433"
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=1Secure*Password1
    volumes:
    - bugdata:/storage/bugs

volumes:
  bugdata: {}